apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Deployment
    metadata:
      name: es
      label:
        app: es
    spec:
      selector:
        matchLabels:
          app: es
      securityContext:
        runAsUser: 1000
      template:
        metadata:
          labels:
            app: es
        spec:
          containers:
            - image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
              name: es
              ports:
                - name: es
                  containerPort: 9200
              env:
                - value: "-Xmx512m -Xms512m"
                  name: ES_JAVA_OPTS
                - value: 0.0.0.0
                  name: network.host
                - value: sommelier-test
                  name: cluster.name
                - value: changeme
                  name: ELASTIC_PASSWORD
                - value: single-node
                  name: discovery.type
              resources:
                limits:
                  memory: 1Gi
                  cpu: 500m
              imagePullPolicy: IfNotPresent

  - apiVersion: v1
    kind: Service
    metadata:
      name: es
    spec:
      ports:
        - port: 9200
          targetPort: es
      selector:
        app: es
