apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Deployment
    metadata:
      name: mongo
      label:
        app: mongo
    spec:
      selector:
        matchLabels:
          app: mongo
      securityContext:
        runAsUser: 999
      template:
        metadata:
          labels:
            app: mongo
        spec:
          containers:
            - image: mongo:4
              name: mongo
              ports:
                - name: mongo
                  containerPort: 27017
              env:
                - value: mongo
                  name: MONGO_INITDB_ROOT_USERNAME
                - value: changeme
                  name: MONGO_INITDB_ROOT_PASSWORD
                - value: sommelier-test
                  name: MONGO_INITDB_DATABASE
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 512Mi
                  cpu: 500m
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo
    spec:
      ports:
        - port: 27017
          targetPort: mongo
      selector:
        app: mongo
