package models

// Address describe postal address
// City, zip code and country must be provided
// ID can be generated by repository when it be created
type Address struct {
	ID      string `json:"id,omitempty"`
	Street  string `json:"street,omitempty"`
	ZipCode string `json:"zip_code" validate:"required"`
	City    string `json:"city" validate:"required"`
	Country string `json:"country" validate:"required"`
}
