package models

// Bottle describe a wine bottle
// ID can be generated by repository when it be created
type Bottle struct {
	ID              string      `json:"id,omitempty"`
	WineEstate      *WineEstate `json:"wine_estate"`
	Name            string      `json:"name,omitempty"`
	Color           string      `json:"color"`
	VintageYear     string      `json:"vintage_year"`
	Size            int         `json:"size"`
	Alcool          float64     `json:"alcool,omitempty"`
	Labels          []string    `json:"labels,omitempty"`
	Description     string      `json:"description,omitempty"`
	OfficialTasting string      `json:"official_tasting,omitempty"`
	GrapeVarieties  []string    `json:"grape_varieties,omitempty"`
	TastingNote     string      `json:"tasting_note,omitempty"`
	TemperatureMin  int         `json:"temperature_min,omitempty"`
	TemperatureMax  int         `json:"temperature_max,omitempty"`
	WineStorageMin  int         `json:"wine_storage_min,omitempty"`
	WineStorageMax  int         `json:"wine_storage_max,omitempty"`
	OfficialPrice   float64     `json:"official_price,omitempty"`
	Awards          []string    `json:"awards,omitempty"`
	BarCode         string      `json:"barcode,omitempty"`
	FilesID         []string    `json:"files_id,omitempty"`
	Note            float64     `json:"note,omitempty"`
}
