package models

// WineEstate describe a wine estate
// Name and region must be provider
// ID can be generated by repository when it be created
type WineEstate struct {
	ID        string   `json:"id,omitempty"`
	Name      string   `json:"name"`
	Producer  string   `json:"producer,omitempty"`
	Region    string   `json:"region"`
	SubRegion string   `json:"sub_region,omitempty"`
	Address   *Address `json:"address,omitempty"`
}
